# To fix metaspace errors
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.kotlin.dsl.allWarningsAsErrors=true


########## Properties for publishing to Maven Central ##########

mavenCentralPublishing=true
mavenCentralAutomaticPublishing=true
mavenCentralDeploymentValidation=NONE
signAllPublications=true

GROUP=com.diffplug.spotless
POM_DESCRIPTION=Spotless - keep your code spotless with Gradle
POM_URL=https://github.com/diffplug/spotless
POM_SCM_URL=https://github.com/diffplug/spotless
POM_SCM_CONNECTION=scm:git:https://github.com/diffplug/spotless.git
POM_SCM_DEV_CONNECTION=scm:git:ssh:git@github.com/diffplug/spotless.git

POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo

POM_DEVELOPER_ID=nedtwigg
POM_DEVELOPER_NAME=Ned Twigg
POM_DEVELOPER_EMAIL=ned.twigg@diffplug.com
