/*
 * Copyright 2016-2024 DiffPlug
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.diffplug.gradle.spotless;

import java.io.IOException;

import org.junit.jupiter.api.Test;

class IdeHookTest extends GradleIntegrationHarness {
	@Test
	void ideHookOnlyChangeSpecificFile() throws IOException {
		setFile("build.gradle").toLines(
				"plugins { id 'com.diffplug.spotless' }",
				"spotless {",
				"  format 'toLower', {",
				"    target '**/*.md'",
				"    custom 'lowercase', { str -> str.toLowerCase() }",
				"  }",
				"}");
		String content = "// Generated by Mr. Roboto, do not edit.\n" +
				"A B C\n" +
				"D E F\n" +
				"G H I";
		setFile("test_generated.md").toContent(content);
		setFile("test_manual.md").toLines(
				"A B C",
				"D E F",
				"G H I");
		gradleRunner().withArguments("spotlessApply", "-PspotlessIdeHook=test_manual.md").build();
		// `test_generated` contains the excluding text so didn't change.
		assertFile("test_generated.md").hasContent(content);
		// `test_manual` does not so it changed.
		assertFile("test_manual.md").hasLines(
				"a b c",
				"d e f",
				"g h i");
	}
}
